version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: citas_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_DATABASE: citasdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1234
    ports:
      - "27827:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: